🔀 :: (#37) 서비스 리스트 가져오기 Api
team-xquare/v1-service-backoffice pull request #42
Opened 2022-10-18 10:29 UTC by leeseojune53

close #37

2022-10-18 10:32 UTC, jhhong0509 requested changes

2022-10-18 10:32 UTC, jhhong0509 commented on src/main/kotlin/io/github/v1servicebackoffice/domain/service/domain/ServiceEntity.kt
> +    fun getServiceUrl() = this.subdomain + "xquare.app" + this.prefix
p3) 이런것도 spring cloud에서 관리하면 좋을듯

2022-10-18 10:32 UTC, jhhong0509 commented on src/main/kotlin/io/github/v1servicebackoffice/domain/service/presentation/ServiceController.kt
> +    fun queryServiceList() = serviceService.queryServiceList()
p2) 이건 반환 타입 정확하게 명시해야할듯

2022-10-18 10:32 UTC, jhhong0509 commented on src/main/kotlin/io/github/v1servicebackoffice/domain/service/service/ServiceService.kt
> +                }
p4) depth가 너무 깊음
바로 파라미터로 넣기보단 변수에 담는게 좋을듯

2022-10-18 10:51 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-10-19 15:16 UTC, leeseojune53 commented on src/main/kotlin/io/github/v1servicebackoffice/domain/service/domain/ServiceEntity.kt
> +    fun getServiceUrl() = this.subdomain + "xquare.app" + this.prefix
요건 추후에 변경. :)

2022-10-19 16:18 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-10-20 00:44 UTC, jhhong0509 approved these changes

2022-10-20 14:05 UTC, merged

2022-10-20 14:31 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃